### ISSUE TITLE
[chapter 1] Is Wint likable enough for a main character?

### ISSUE THREAD

**Issue by jevakallio** [jevakallio/NaNoWriMo#1]
Based on the [first chapter](https://github.com/jevakallio/NaNoWriMo/blob/master/chapters/01.md) alone, I'm wondering whether I framed Wint as someone people would want to continue to follow? 

He is intended to be a flawed character, and changing in these regards is part of his growth through the story. But if this is the starting point, will people fail to care for him because he comes off as too much of a loser or too much of a chauvinist?

The theory is that people empathise when bad things happen to good people. In my head I know he's good people because I know where the story is going, but did I forget to make him good people on the page?

Were you able to empathise with him despite his flaws? Did you feel at all sorry for him when things went wrong? Based on your first reactions, should have I made him a little bit nicer? 

(We will not be following him around the whole book, there are plenty of characters with different points of view.)

**Comment by kadikraman** [comment]
I’m cheating a bit, because I also read the second chapter, but I didn’t really care for him in the first one. I was imagining him as more of a failed journalist rather than one that wasn’t keen on moving with the times. I liked the date recollection though, it was funny. But in the second chapter, he became more likable because his secretary liked him, and also had a better career than it seemed in chapter 1 due to having his own office. I was imagining a boring office job. Maybe because he took a bus to work. I don’t think anyone high up would take a bus to work.

**Comment by husebo** [comment]
Having only read chapter 1, I feel like he's slightly pitiable, definitely not very likeable, and his "not too tech savvy" seems a bit extreme if he's never bought anything online - that's just stubborn and arguably silly in London.

But I'm interested in continuing because I want to know more about him. Are you considering giving him some more redeeming qualities in the first chapter already?

**Comment by jevakallio** [comment]
@kadikraman thank you, that is very helpful! You pointed out a couple of implicit issues I had missed - he was not supposed to come off as a big boss and definitely not wealthy. Will fix those in edits to Chapter 2, and see if I can make him less failed in Chapter 1.

**Comment by jevakallio** [comment]
@husebo our man has a complicated relationship to tech, more about that in Chapter 3. But you are right, "never shopped online" is too extreme, I can fix that.

I do also want to make him more likeable in Chapter 1, it was always the plan but the scene just came out this way. Need more "normalcy" before things start going wrong

**Comment by jevakallio** [comment]
Thanks for the feedback! These have been (hopefully) fixed by #6!
